spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/test_db?useSSL=false
    username: test_user
    password: test_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://192.168.99.100:3306/test_db?allowPublicKeyRetrieval=true&useSSL=false
    user: test_user
    password: test_password

mybatis:
  configuration:
      map-underscore-to-camel-case: true
      default-fetch-size: 100
      default-statement-timeout: 30
      
